from collections.abc import Callable

import pytest

from cobol_to_python import LexerError, ParseError, SemanticError, transpile

ACCEPTED_PROGRAMS = (
    """IDENTIFICATION DIVISION.
PROGRAM-ID. HELLO.
DATA DIVISION.
WORKING-STORAGE SECTION.
PROCEDURE DIVISION.
DISPLAY "Hello, world!".
STOP RUN.""",
    """IDENTIFICATION DIVISION.
PROGRAM-ID. TOTALS.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 FIRST-NUMBER PIC 9(3) VALUE 12.
01 SECOND-NUMBER PIC 9(3) VALUE 8.
01 TOTAL PIC 9(4).
PROCEDURE DIVISION.
COMPUTE TOTAL = FIRST-NUMBER + SECOND-NUMBER * 2.
DISPLAY TOTAL.
STOP RUN.""",
    """IDENTIFICATION DIVISION.
PROGRAM-ID. GREETING.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 NAME PIC X(10) VALUE "Ada".
01 COUNT PIC 9(2) VALUE 3.
PROCEDURE DIVISION.
IF COUNT >= 1
    DISPLAY NAME.
ELSE
    DISPLAY "Nobody".
END-IF.
MOVE "Grace" TO NAME.
DISPLAY NAME.
STOP RUN.""",
    """IDENTIFICATION DIVISION.
PROGRAM-ID. CLASSIFY.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 VALUE-A PIC 9(2) VALUE 5.
01 VALUE-B PIC 9(2) VALUE 8.
PROCEDURE DIVISION.
*> Compare the two values.
IF VALUE-A < VALUE-B
    IF VALUE-A = 5
        DISPLAY "MATCH".
    ELSE
        DISPLAY "LOWER".
    END-IF.
ELSE
    DISPLAY "NOT-LOWER".
END-IF.
STOP RUN.""",
)


def execute(generated: str) -> Callable[[], None]:
    namespace: dict[str, object] = {"__name__": "transpiled_test"}
    exec(compile(generated, "<transpiled>", "exec"), namespace)
    main = namespace["main"]
    assert callable(main)
    return main


@pytest.mark.parametrize("source", ACCEPTED_PROGRAMS)
def test_transpiles_every_documented_accepted_program(source: str) -> None:
    generated = transpile(source)

    assert generated.startswith('"""Generated by cobol-to-python.')
    compile(generated, "<transpiled>", "exec")


def test_transpiled_documented_program_executes(
    capsys: pytest.CaptureFixture[str],
) -> None:
    execute(transpile(ACCEPTED_PROGRAMS[1]))()

    assert capsys.readouterr().out == "28\n"


def complete_program(*, data: str = "", procedure: str = "") -> str:
    return f"""IDENTIFICATION DIVISION.
PROGRAM-ID. REJECTED.
DATA DIVISION.
WORKING-STORAGE SECTION.
{data}PROCEDURE DIVISION.
{procedure}STOP RUN."""


def test_fixed_format_source_is_rejected_during_parsing() -> None:
    source = """000100 IDENTIFICATION DIVISION.
000200 PROGRAM-ID. FIXED.
000300 DATA DIVISION.
000400 WORKING-STORAGE SECTION.
000500 PROCEDURE DIVISION.
000600 STOP RUN."""

    with pytest.raises(ParseError) as error:
        transpile(source)

    assert error.value.token.span.start.line == 1
    assert error.value.token.span.start.column == 1


@pytest.mark.parametrize(
    "source",
    [
        complete_program(data="01 9COUNT PIC 9(2).\n"),
        complete_program(procedure='DISPLAY "HELLO.\n'),
    ],
)
def test_documented_lexical_errors_propagate(source: str) -> None:
    with pytest.raises(LexerError):
        transpile(source)


def test_missing_end_if_is_a_parse_error() -> None:
    source = complete_program(procedure='IF COUNT = 1\nDISPLAY "ONE".\n')

    with pytest.raises(ParseError) as error:
        transpile(source)

    assert error.value.token.lexeme == "STOP"


@pytest.mark.parametrize(
    "source",
    [
        complete_program(
            data="01 COUNT PIC 9(2).\n",
            procedure='MOVE "TEN" TO COUNT.\n',
        ),
        complete_program(procedure="DISPLAY MISSING-NAME.\n"),
    ],
)
def test_documented_semantic_errors_propagate(source: str) -> None:
    with pytest.raises(SemanticError):
        transpile(source)


@pytest.mark.parametrize(
    "source",
    [
        complete_program(procedure="PERFORM CALCULATE-TOTAL.\n"),
        complete_program(data="01 PRICE PIC 9(3)V99.\n"),
    ],
)
def test_documented_unsupported_syntax_is_rejected(source: str) -> None:
    with pytest.raises(ParseError):
        transpile(source)


def test_transpile_is_deterministic() -> None:
    assert transpile(ACCEPTED_PROGRAMS[0]) == transpile(ACCEPTED_PROGRAMS[0])
